[package]
name = "bal-syntax"
version.workspace = true
edition.workspace = true

[dependencies]
rowan.workspace = true
logos.workspace = true
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
thiserror = "1.0" 